modules = [
  "app",
  "wevra.web",
  "wevra.auth",
]

[routes."app"]
default = ""

[routes."wevra.web"]
partials = ""
api = ""

[routes."wevra.auth"]
account = "/account"
api = ""

[templates]
auto_reload = true
cache_size = 0

[static]
url_path = "/static/"
export_root = "static"
